"""empty message

Revision ID: c063378ddca2
Revises: 8cb5809b66d3
Create Date: 2020-08-05 04:47:27.823802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c063378ddca2'
down_revision = '8cb5809b66d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('nickname', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'nickname')
    # ### end Alembic commands ###
